export type { IRouteRepository, Disposable } from './route-repository.js'
export type { IProxyServer } from './proxy-server.js'
export type { ICertificateManager, SNICallback } from './certificate-manager.js'
export type { IHostsManager } from './hosts-manager.js'
export type { IPortAllocator } from './port-allocator.js'
export type { IProcessManager } from './process-manager.js'
export type { ILogger } from './logger.js'
export type { IGitAdapter, WorktreeResult } from './git-adapter.js'
export type { IProjectDetector, InferredProject } from './project-detector.js'
export type { IStateManager, ProxyState } from './state-manager.js'
export type { IComposeAdapter, ComposeServiceInfo } from './compose-adapter.js'
